version: '3.7'

services:
  screenshot:
    image: eeacms/screenshoteer:latest
    environment:
        VOLUME: '/tmpScreens/'
        TZ: 'Europe/Copenhagen'
    volumes:
      - ./tmpScreens:/tmpScreens
    ports:
      - "3000:3000"
    cap_add:
      - SYS_ADMIN
    init: true
