version: '3.7'

services:
  screenshot:
    image: eeacms/screenshoteer:latest
    environment:
        VOLUME: '/tmpScreens/'
        CHROME_DEVEL_SANDBOX: '/usr/local/sbin/chrome-devel-sandbox'
        TZ: 'Europe/Copenhagen'
        # DEBUG: 'puppeteer:* env DEBUG_COLORS=true node script.js 2>&1 | grep -v "Network"'
    volumes:
      - ./tmpScreens:/tmpScreens
    ports:
      - "3000:3000"
    cap_add:
      - SYS_ADMIN
    init: true
